// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ejemplo2.Migrations
{
    [DbContext(typeof(LibrosDBContext))]
    [Migration("20260730030931_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ejemplo2.Models.Autor", b =>
                {
                    b.Property<int>("CodAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("CodAutor");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("Ejemplo2.Models.Libro", b =>
                {
                    b.Property<int>("CodLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<int>("AutorCodAutor")
                        .HasColumnType("int");

                    b.Property<int>("CodAutor")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("CodLibro");

                    b.HasIndex("AutorCodAutor");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("Ejemplo2.Models.Libro", b =>
                {
                    b.HasOne("Ejemplo2.Models.Autor", "Autor")
                        .WithMany("Libros")
                        .HasForeignKey("AutorCodAutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Ejemplo2.Models.Autor", b =>
                {
                    b.Navigation("Libros");
                });
#pragma warning restore 612, 618
        }
    }
}
