// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ejemplo2.Migrations
{
    [DbContext(typeof(LibrosDBContext))]
    partial class LibrosDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ejemplo2.Models.Autor", b =>
                {
                    b.Property<int>("CodAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("CodAutor");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("Ejemplo2.Models.Libro", b =>
                {
                    b.Property<int>("CodLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<int>("AutorCodAutor")
                        .HasColumnType("int");

                    b.Property<int>("CodAutor")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("CodLibro");

                    b.HasIndex("AutorCodAutor");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("Ejemplo2.Models.Prestamo", b =>
                {
                    b.Property<int>("CodPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CodLibro")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDevolucion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LibroCodLibro")
                        .HasColumnType("int");

                    b.HasKey("CodPrestamo");

                    b.HasIndex("LibroCodLibro");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("Ejemplo2.Models.Libro", b =>
                {
                    b.HasOne("Ejemplo2.Models.Autor", "Autor")
                        .WithMany("Libros")
                        .HasForeignKey("AutorCodAutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Ejemplo2.Models.Prestamo", b =>
                {
                    b.HasOne("Ejemplo2.Models.Libro", "Libro")
                        .WithMany()
                        .HasForeignKey("LibroCodLibro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("Ejemplo2.Models.Autor", b =>
                {
                    b.Navigation("Libros");
                });
#pragma warning restore 612, 618
        }
    }
}
